
name: Nightly Builds

# Run the nightly tests at at 8 AM UTC / 2 AM Central
on:
  schedule:
    - cron: "0 8 * * *"

jobs:
  kind2-static-bin:
    if: github.repository == 'kind2-mc/kind2'
    strategy:
      matrix:
        os: [ ubuntu-20.04 ]

    runs-on: ${{ matrix.os }}
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        driver-opts: network=host

    - name: Build and push to local registry
      uses: docker/build-push-action@v2
      with:
        file: docker/Dockerfile.StaticBuild
        context: ./
        push: true
        tags: localhost:5000/name/kind2:latest
    
    - name: Extract kind 2 binary
      id: extract
      uses: shrink/actions-docker-extract@v1
      with:
        image: localhost:5000/name/kind2:latest
        path: /kind2

    - name: Upload kind2 binary
      uses: actions/upload-artifact@v2
      with:
        path: ${{ steps.extract.outputs.destination }}
        name: kind2-linux-static

  kind2-dynamic-bin:
    if: github.repository == 'kind2-mc/kind2'
    strategy:
      matrix:
        ocaml-version: [ 4.11.1 ]
        os: [ ubuntu-18.04, macos-10.15 ]
        include:
          - os: macos-10.15
            zmq_install: brew install zmq
          - os: ubuntu-18.04
            zmq_install: sudo apt-get install -y libzmq3-dev

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Cache opam repository
      uses: actions/cache@v2
      with:
        path: ~/.opam
        key: ${{ matrix.os }}-opam-${{ matrix.ocaml-version }}

    - name: Set up OCaml ${{ matrix.ocaml-version }}
      uses: avsm/setup-ocaml@v1
      with:
        ocaml-version: ${{ matrix.ocaml-version }}

    - name: Install ZMQ library
      run: ${{ matrix.zmq_install }}

    - name: Install Kind2 OCaml dependencies
      run: opam install -y . --deps-only

    - name: Build Kind 2
      run: opam exec make

    - name: Strip binary
      run: strip bin/kind2

    - name: Upload Kind 2 binary
      uses: actions/upload-artifact@v2
      with:
        name: kind2-${{ matrix.os }}
        path: bin/kind2

  nightly-release:
    if: github.repository == 'kind2-mc/kind2'
    strategy:
      matrix:
        os: [ ubuntu-20.04 ]

    needs: [kind2-static-bin, kind2-dynamic-bin]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download binaries
      uses: actions/download-artifact@v2

    - name: Create tar.gz files
      run: |
        chmod u+x ./kind2-*/kind2
        tar -czf kind2-linux-static.tar.gz -C ./kind2-linux-static/ kind2
        tar -czf kind2-ubuntu-18.04.tar.gz -C ./kind2-ubuntu-18.04/ kind2
        tar -czf kind2-macos-10.15.tar.gz -C ./kind2-macos-10.15/ kind2
    
    - name: Update nightly tag
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git tag -f nightly-dev
        git push --tags -f

    - name: Get nightly pre-release
      uses: octokit/request-action@v2.x
      id: get_nightly_prerelease
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        route: GET /repos/:repository/releases/tags/nightly-dev
        repository: ${{ github.repository }}

    - name: Get pre-release upload_url
      id: get_upload_url
      run: |
        url=$(echo "$response" | jq -r '.upload_url')
        echo "::set-output name=url::$url"
      env:
        response: ${{ steps.get_nightly_prerelease.outputs.data }}

    - name: Get previous asset ids
      id: get_asset_ids
      run: |
        linux_id=$(echo "$response" | jq '.assets | .[] | select(.name == "kind2-linux-static.tar.gz") | .id')
        ubuntu_id=$(echo "$response" | jq '.assets | .[] | select(.name == "kind2-ubuntu-18.04.tar.gz") | .id')
        macos_id=$(echo "$response" | jq '.assets | .[] | select(.name == "kind2-macos-10.15.tar.gz") | .id')
        echo "::set-output name=linux_id::${linux_id:-0}"
        echo "::set-output name=ubuntu_id::${ubuntu_id:-0}"
        echo "::set-output name=macos_id::${macos_id:-0}"
      env:
        response: ${{ steps.get_nightly_prerelease.outputs.data }}

    - name: Remove previous Linux static artifact
      if: steps.get_asset_ids.outputs.linux_id != 0
      uses: octokit/request-action@v2.x
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        route: DELETE /repos/:repository/releases/assets/:asset_id
        repository: ${{ github.repository }}
        asset_id: ${{ steps.get_asset_ids.outputs.linux_id }}

    - name: Upload Linux static artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_upload_url.outputs.url }}
        asset_path: kind2-linux-static.tar.gz
        asset_name: kind2-linux-static.tar.gz
        asset_content_type: application/gzip

    - name: Remove previous Ubuntu artifact
      if: steps.get_asset_ids.outputs.ubuntu_id != 0
      uses: octokit/request-action@v2.x
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        route: DELETE /repos/:repository/releases/assets/:asset_id
        repository: ${{ github.repository }}
        asset_id: ${{ steps.get_asset_ids.outputs.ubuntu_id }}

    - name: Upload Ubuntu artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_upload_url.outputs.url }}
        asset_path: kind2-ubuntu-18.04.tar.gz
        asset_name: kind2-ubuntu-18.04.tar.gz
        asset_content_type: application/gzip

    - name: Remove previous macOS artifact
      if: steps.get_asset_ids.outputs.macos_id != 0
      uses: octokit/request-action@v2.x
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        route: DELETE /repos/:repository/releases/assets/:asset_id
        repository: ${{ github.repository }}
        asset_id: ${{ steps.get_asset_ids.outputs.macos_id }}

    - name: Upload macOS artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_upload_url.outputs.url }}
        asset_path: kind2-macos-10.15.tar.gz
        asset_name: kind2-macos-10.15.tar.gz
        asset_content_type: application/gzip
